# -*- coding: utf-8 -*-
"""ai_learning_intelligence_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ToGsQ4EhyQgdbN_rFri-CND5Y6ToFLj
"""

# Installing all required libraries
!pip install chromadb sentence-transformers anthropic -q

# Verify installations
import chromadb
import sentence_transformers
import anthropic

print("ChromaDB version:", chromadb.__version__)
print("Sentence Transformers version:", sentence_transformers.__version__)
print("Anthropic version:", anthropic.__version__)
print("\nAll libraries installed successfully!")

# ── KNOWLEDGE BASE ──
# Your personal AI/ML study notes
# Each entry = one document in ChromaDB
# Format: {"id": unique_id, "topic": category, "title": title, "content": full text}

knowledge_base = [

    # ── PYTHON FOR AI/ML ──
    {
        "id": "py_001",
        "topic": "Python for AI/ML",
        "title": "Python data structures for AI",
        "content": """
        Python is the primary language for AI/ML work. The most important data structures are:
        Lists: ordered collections used to store datasets. Example: labels = ['cat', 'dog', 'bird']
        Dictionaries: key-value pairs used for annotation records. Example: {"id": 1, "label": "cat", "confidence": 0.95}
        List of dictionaries: the most common data format in annotation pipelines.
        List comprehensions: compact filtering syntax. Example: [item for item in dataset if item['label'] == 'cat']
        JSON: JavaScript Object Notation - the standard format for annotation exports and API responses.
        Reading JSON files uses json.load(). Writing uses json.dump() with indent=2 for readability.
        """
    },
    {
        "id": "py_002",
        "topic": "Python for AI/ML",
        "title": "Pandas for data analysis",
        "content": """
        Pandas is the industry standard library for working with tabular data in AI/ML.
        Key operations: df.head() shows first 5 rows. df.value_counts() counts label frequencies.
        Filtering: df[df['label'] == 'cat'] selects rows matching a condition.
        Column operations: df['text'] = df['text'].str.lower() transforms entire columns.
        Saving: df.to_csv('output.csv', index=False) saves clean CSV files.
        Pandas DataFrames are used to analyze annotation datasets, track label distributions,
        and export results after annotation projects are complete.
        """
    },
    {
        "id": "py_003",
        "topic": "Python for AI/ML",
        "title": "API calls in Python",
        "content": """
        APIs allow Python to communicate with external services like LLMs.
        The requests library is used for generic HTTP API calls.
        Pattern: response = requests.post(url, headers=headers, json=data)
        The Anthropic SDK is used for Claude API calls.
        The OpenAI SDK is used for GPT API calls.
        API keys should never be hardcoded - use environment variables or secure storage.
        Response parsing: data = response.json() converts JSON response to Python dictionary.
        Error handling with try/except prevents crashes when API calls fail.
        """
    },

    # ── DATA ANNOTATION ──
    {
        "id": "ann_001",
        "topic": "Data Annotation",
        "title": "What is data annotation and why it exists",
        "content": """
        Data annotation is the process of labeling raw data so AI models can learn from it.
        AI models learn from examples - they need thousands of correctly labeled items to learn patterns.
        Without annotation there is no training data. Without training data there is no AI model.
        The annotation pipeline: raw data → human annotation → labeled dataset → model training → AI model.
        Types of annotation: text classification, named entity recognition, bounding boxes,
        image segmentation, RLHF rating, transcription, ranking and preference annotation.
        Annotation quality directly determines model quality - garbage in, garbage out.
        Companies like Scale AI, Surge AI, and Labelbox manage large annotation operations.
        """
    },
    {
        "id": "ann_002",
        "topic": "Data Annotation",
        "title": "Annotation quality and inter-annotator agreement",
        "content": """
        Annotation quality is measured through inter-annotator agreement (IAA).
        IAA measures how consistently different annotators label the same data.
        High IAA means labels are reliable and guidelines are clear.
        Low IAA means annotators interpret guidelines differently - leads to noisy training data.
        Gold standard sets are pre-labeled items mixed invisibly into batches to measure accuracy.
        Annotators don't know which items are gold standard - their score reveals true accuracy.
        Quality control uses three layers: gold standard items, IAA monitoring, and spot checks.
        Edge cases should be flagged and escalated rather than guessed - accuracy beats speed.
        Annotation throughput is measured in items per hour alongside accuracy scores.
        """
    },
    {
        "id": "ann_003",
        "topic": "Data Annotation",
        "title": "Labelbox annotation platform",
        "content": """
        Labelbox is an enterprise annotation platform used by Google, Walmart, Ford, and others.
        Key workflow: upload data to Catalog → create ontology → send to project → annotate → export.
        Ontology defines the label schema - what classifications annotators can apply.
        Ontology types: radio buttons for single choice, checkboxes for multi-select, text for free input.
        Data rows are individual items in the annotation queue.
        Batches group data rows for organized workflow management.
        Export formats: JSON and NDJSON (Newline Delimited JSON).
        NDJSON is the industry standard for large annotation exports - each line is one record.
        The Labelbox Python SDK allows programmatic data upload and management.
        Performance metrics tracked: seconds to label, accuracy on gold standards, IAA scores.
        """
    },
    {
        "id": "ann_004",
        "topic": "Data Annotation",
        "title": "RLHF and human feedback in LLM training",
        "content": """
        RLHF stands for Reinforcement Learning from Human Feedback.
        It is the technique used to train ChatGPT, Claude, and Gemini to be helpful and safe.
        Stage 1 - Pre-training: model trains on 500B+ words of internet text with no annotation.
        Stage 2 - Supervised fine-tuning: annotators write 10,000-50,000 ideal question-answer pairs.
        Stage 3 - RLHF: annotators compare pairs of model outputs and rate which is better.
        These ratings train a reward model which then trains the LLM to produce preferred outputs.
        RLHF annotation involves rating helpfulness, accuracy, safety, and tone of AI responses.
        Scale AI and Surge AI run major RLHF programs for OpenAI, Meta, and other AI labs.
        Hallucination detection annotation is a critical part of RLHF quality control pipelines.
        """
    },

    # ── LLM ARCHITECTURES ──
    {
        "id": "llm_001",
        "topic": "LLM Architectures",
        "title": "What is a Large Language Model",
        "content": """
        A Large Language Model is a statistical system trained to predict the next token given previous tokens.
        LLMs learn patterns from massive text datasets - books, websites, code, scientific papers.
        Parameters are the learned numbers in the model - GPT-4 has approximately 1.8 trillion parameters.
        More parameters generally means better performance on complex and rare tasks.
        Tokens are the basic units LLMs process - typically 3-4 characters each, not full words.
        1000 tokens is approximately 750 words in English.
        Emergent abilities: capabilities like reasoning and coding emerge from scale - nobody programmed them explicitly.
        Training is expensive - GPT-4 cost an estimated $100 million to train.
        Inference is running the trained model to generate responses - much cheaper than training.
        """
    },
    {
        "id": "llm_002",
        "topic": "LLM Architectures",
        "title": "Transformer architecture and attention",
        "content": """
        The transformer architecture was introduced by Google in 2017 in the paper Attention Is All You Need.
        All modern LLMs including GPT-4, Claude, Gemini, and LLaMA are built on transformers.
        The key innovation is the attention mechanism - allows the model to look at all other tokens
        when predicting the next token, not just nearby ones.
        Self-attention lets the model connect distant words - resolving pronouns like 'it' back to the noun.
        The 4-step pipeline: input text → tokenize → attention layers → predict next token → output text.
        Context window is how much text the model can see at once - GPT-4 has 128,000 tokens.
        Larger context windows allow processing longer documents but cost more compute.
        Fine-tuning adapts a pre-trained model to a specific task using a smaller labeled dataset.
        """
    },
    {
        "id": "llm_003",
        "topic": "LLM Architectures",
        "title": "Major LLM models and their characteristics",
        "content": """
        GPT-4o by OpenAI: multimodal model handling text, images, and audio. 128k context window.
        Claude 3.5 by Anthropic: strong at long documents and coding. 200k context window. Safety-focused.
        Gemini 1.5 Pro by Google: 1 million token context window. Natively multimodal.
        LLaMA 3 by Meta: open source model freely downloadable and runnable locally.
        Mistral 7B: efficient open source model that rivals larger closed models on many benchmarks.
        Command R+ by Cohere: enterprise model specifically optimized for RAG pipelines.
        Open source models allow fine-tuning and local deployment without API costs or privacy concerns.
        Closed models like GPT-4 and Claude offer the best performance but require API access.
        """
    },

    # ── PROMPT ENGINEERING ──
    {
        "id": "pe_001",
        "topic": "Prompt Engineering",
        "title": "Core prompt engineering techniques",
        "content": """
        Prompt engineering is the skill of writing instructions that reliably produce desired AI outputs.
        Zero-shot prompting: ask directly with no examples. Works for simple clear tasks.
        Few-shot prompting: provide 2-5 input-output examples before the real question.
        Few-shot dramatically improves consistency - examples teach the labeling standard better than rules.
        System prompts: set the AI role and behavior before conversation. Every production app uses these.
        Chain of thought: ask the AI to think step by step before answering. Improves complex reasoning.
        Output formatting: specify exact JSON, CSV, or structured format for programmatic parsing.
        Prompt templates: reusable prompts with placeholder variables filled at runtime.
        The golden rule: treat AI like a brilliant new employee - give role, context, constraints, format.
        """
    },
    {
        "id": "pe_002",
        "topic": "Prompt Engineering",
        "title": "Prompt engineering for annotation tasks",
        "content": """
        Prompt engineering is critical for automated annotation pipelines.
        Classification prompt structure: role + task + options + format + example input.
        Always constrain output to valid labels only - prevents invalid label generation.
        Chain of thought improves accuracy on safety evaluation and edge case classification.
        Few-shot examples should cover edge cases not just clear-cut examples.
        JSON output format is essential for parsing results programmatically in annotation pipelines.
        System prompt should define the annotator role and annotation standard precisely.
        Prompt versioning: track which prompt version produced which annotation batch for auditability.
        Temperature setting: use low temperature (0.1-0.3) for classification tasks requiring consistency.
        """
    },

    # ── RAG ──
    {
        "id": "rag_001",
        "topic": "RAG",
        "title": "RAG fundamentals and why it matters",
        "content": """
        RAG stands for Retrieval Augmented Generation.
        RAG solves two core LLM problems: knowledge cutoff and hallucination.
        Knowledge cutoff: LLMs only know information from their training data cutoff date.
        Hallucination: LLMs confidently generate plausible but incorrect information about unknown topics.
        RAG solution: retrieve relevant documents from an external knowledge base at query time,
        include them in the prompt, and instruct the LLM to answer only from those documents.
        RAG pipeline: question → embed question → search vector database → retrieve top-k chunks →
        build augmented prompt → LLM generates grounded answer with citations.
        RAG enables unlimited knowledge base size - only relevant chunks enter the context window.
        Enterprise RAG systems keep sensitive data on-premise for security and compliance.
        """
    },
    {
        "id": "rag_002",
        "topic": "RAG",
        "title": "RAG chunking and retrieval strategies",
        "content": """
        Chunking is splitting documents into smaller pieces for storage and retrieval.
        Chunk size affects retrieval quality: too small loses context, too large dilutes relevance.
        Typical chunk size: 200-500 words with 50-word overlap between chunks.
        Overlap prevents important information from being split across chunk boundaries.
        Top-k retrieval: retrieve the k most similar chunks. Typically k=3 to k=5.
        Too few chunks misses relevant context. Too many fills context window with noise.
        Similarity threshold: only retrieve chunks above a minimum similarity score.
        Low similarity score = knowledge gap - the answer is not in the knowledge base.
        Hybrid search combines vector similarity with keyword matching for better precision.
        Reranking: use a second model to reorder retrieved chunks by relevance after initial retrieval.
        """
    },

    # ── VECTOR DATABASES ──
    {
        "id": "vdb_001",
        "topic": "Vector Databases",
        "title": "Vector databases and embeddings",
        "content": """
        A vector database stores data as vectors - lists of numbers representing meaning.
        Embeddings convert text into vectors that capture semantic meaning.
        Similar meanings produce similar vectors - vacation policy and PTO rules are close in vector space.
        Embedding models: text-embedding-3-small by OpenAI, all-MiniLM-L6-v2 by HuggingFace (free).
        Cosine similarity measures angle between vectors - score of 1.0 means identical meaning.
        The three core operations: upsert (store), query (search), delete (remove).
        Vector databases enable semantic search - finding by meaning not exact keywords.
        FAISS by Meta: open source similarity search library used in production at massive scale.
        ChromaDB: easiest to use, runs locally, perfect for portfolio projects and prototypes.
        Pinecone: managed cloud vector database that scales automatically for production systems.
        """
    },
    {
        "id": "vdb_002",
        "topic": "Vector Databases",
        "title": "Building RAG with ChromaDB",
        "content": """
        ChromaDB is an open source vector database that runs locally with zero configuration.
        Installation: pip install chromadb sentence-transformers.
        Creating a client: client = chromadb.Client()
        Creating a collection: collection = client.create_collection('name')
        Adding documents: collection.add(documents=docs, embeddings=embeddings, ids=ids)
        Querying: results = collection.query(query_embeddings=query_emb, n_results=3)
        Results contain documents, distances, and metadata for each retrieved chunk.
        Distance score: lower distance means higher similarity in ChromaDB's default metric.
        Persistent storage: use chromadb.PersistentClient(path='./db') to save to disk.
        sentence-transformers library provides free local embedding generation.
        all-MiniLM-L6-v2 model produces 384-dimensional embeddings suitable for most RAG tasks.
        """
    },

    # ── AGENTIC AI ──
    {
        "id": "agent_001",
        "topic": "Agentic AI",
        "title": "What are AI agents and agentic systems",
        "content": """
        An AI agent is a system that uses an LLM to autonomously complete multi-step tasks.
        Agents differ from chatbots: chatbots respond, agents act and make decisions.
        Core components: LLM brain, tools the agent can use, memory system, planning capability.
        Tools are functions the agent can call: web search, calculator, database query, API calls.
        Memory types: in-context memory (conversation history), external memory (vector database).
        ReAct pattern: Reason then Act - agent thinks about what to do then takes an action.
        Multi-agent systems: multiple specialized agents collaborate to complete complex tasks.
        LangChain and LangGraph are the dominant frameworks for building agentic systems.
        MCP (Model Context Protocol) by Anthropic is an emerging standard for agent tool integration.
        Agentic AI systems are the fastest growing category in AI engineering in 2025-2026.
        """
    },
    {
        "id": "agent_002",
        "topic": "Agentic AI",
        "title": "LangChain for building AI agents",
        "content": """
        LangChain is the most widely used framework for building LLM applications and agents.
        Core abstractions: chains (sequences of steps), agents (autonomous decision makers), tools (functions).
        LangChain connects LLMs to external tools: search engines, databases, APIs, code executors.
        LangGraph extends LangChain with graph-based agent workflows for complex multi-step tasks.
        Memory integration: LangChain connects to ChromaDB and other vector databases for agent memory.
        RAG chains: document loader → text splitter → embeddings → vector store → retrieval chain.
        Agent executor: manages the loop of agent reasoning, tool selection, and tool execution.
        Common use cases: document Q&A, automated research, code generation agents, data pipelines.
        LangChain is mentioned in over 60% of Agentic AI internship job descriptions in 2026.
        """
    },

    # ── MLOPS ──
    {
        "id": "mlops_001",
        "topic": "MLOps",
        "title": "MLOps basics for AI engineers",
        "content": """
        MLOps is the practice of deploying and maintaining machine learning models in production.
        Git is the foundation: version control for code, notebooks, and configuration files.
        Docker containers package code with its dependencies for consistent deployment anywhere.
        CI/CD pipelines automatically test and deploy code changes.
        Model versioning tracks which model version is running in production and when it was deployed.
        Monitoring tracks model performance over time - detecting when accuracy degrades.
        Data versioning tracks which training data produced which model - critical for debugging.
        Experiment tracking tools like Weights and Biases log hyperparameters and metrics.
        Feature stores centralize data preprocessing for consistent features across training and serving.
        Cloud platforms AWS SageMaker, Azure ML, and GCP Vertex AI provide managed MLOps infrastructure.
        """
    },
]

print(f"Knowledge base created: {len(knowledge_base)} documents")
print("\nTopics covered:")
topics = {}
for doc in knowledge_base:
    topics[doc['topic']] = topics.get(doc['topic'], 0) + 1
for topic, count in topics.items():
    print(f"  {topic}: {count} documents")

from sentence_transformers import SentenceTransformer
import time

# ── Load embedding model ──
print("Loading embedding model...")
print("(This downloads ~90MB the first time — takes 30-60 seconds)")

embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
print("Embedding model loaded!")

# ── Generate embeddings for all documents ──
print("\nGenerating embeddings for all 19 documents...")
start = time.time()

# Extract just the content text for embedding
texts = []
for doc in knowledge_base:
    # Combine title + content for richer embedding
    combined = f"{doc['title']}. {doc['content'].strip()}"
    texts.append(combined)

# Generate all embeddings at once (batch processing)
embeddings = embedding_model.encode(
    texts,
    show_progress_bar=True,
    batch_size=8
)

elapsed = time.time() - start

print(f"\nEmbeddings generated in {elapsed:.1f} seconds")
print(f"Total embeddings: {len(embeddings)}")
print(f"Embedding dimensions: {embeddings.shape[1]}")
print(f"Each document is now a vector of {embeddings.shape[1]} numbers")

# Show sample embedding for first document
print(f"\nSample — first 5 numbers of '{knowledge_base[0]['title']}':")
print(embeddings[0][:5].tolist())

import chromadb

# ── Create ChromaDB client and collection ──
chroma_client = chromadb.Client()

# Delete collection if it already exists (clean start)
try:
    chroma_client.delete_collection("ai_learning_kb")
    print("Existing collection deleted — starting fresh")
except:
    pass

collection = chroma_client.create_collection(
    name="ai_learning_kb",
    metadata={"description": "AI/ML learning knowledge base for RAG system"}
)
print("ChromaDB collection created: ai_learning_kb")

# ── Store all documents with embeddings and metadata ──
print("\nStoring 19 documents in ChromaDB...")

collection.add(
    ids=[doc['id'] for doc in knowledge_base],
    embeddings=embeddings.tolist(),
    documents=[doc['content'].strip() for doc in knowledge_base],
    metadatas=[{
        "title": doc['title'],
        "topic": doc['topic'],
        "id": doc['id']
    } for doc in knowledge_base]
)

# ── Verify storage ──
count = collection.count()
print(f"Documents stored: {count}")
print("\nSample — first 3 stored documents:")
sample = collection.get(
    ids=['py_001', 'ann_001', 'rag_001'],
    include=['metadatas']
)
for meta in sample['metadatas']:
    print(f"  ✓ [{meta['topic']}] {meta['title']}")

print("\nChromaDB storage complete!")
print("Your knowledge base is now searchable by meaning.")

def retrieve(query, n_results=3, min_confidence=0.3):
    """
    Retrieve most relevant documents for a query.

    Args:
        query: natural language question
        n_results: number of documents to retrieve (top-k)
        min_confidence: minimum confidence threshold (0-1)

    Returns:
        dict with retrieved docs, scores, and confidence assessment
    """

    # Step 1 — embed the query
    query_embedding = embedding_model.encode([query]).tolist()

    # Step 2 — search ChromaDB
    results = collection.query(
        query_embeddings=query_embedding,
        n_results=n_results,
        include=['documents', 'metadatas', 'distances']
    )

    # Step 3 — convert distances to confidence scores
    # ChromaDB returns L2 distances — lower = more similar
    # Convert to 0-1 confidence: confidence = 1 / (1 + distance)
    retrieved = []
    for i in range(len(results['documents'][0])):
        distance = results['distances'][0][i]
        confidence = round(1 / (1 + distance), 3)

        retrieved.append({
            'content':    results['documents'][0][i],
            'title':      results['metadatas'][0][i]['title'],
            'topic':      results['metadatas'][0][i]['topic'],
            'id':         results['metadatas'][0][i]['id'],
            'confidence': confidence,
            'distance':   round(distance, 4)
        })

    # Step 4 — assess overall retrieval confidence
    if retrieved:
        top_confidence = retrieved[0]['confidence']
        if top_confidence >= 0.6:
            assessment = "HIGH"
        elif top_confidence >= min_confidence:
            assessment = "MEDIUM"
        else:
            assessment = "LOW — possible knowledge gap"
    else:
        assessment = "NO RESULTS"
        top_confidence = 0.0

    return {
        'query':          query,
        'results':        retrieved,
        'top_confidence': top_confidence,
        'assessment':     assessment,
        'gap_detected':   top_confidence < min_confidence
    }


# ── Test the retrieval function ──
print("Testing retrieval function...\n")

test_queries = [
    "What is RAG and how does it work?",
    "How does inter-annotator agreement work?",
    "What is a transformer in AI?",
    "How do I use ChromaDB in Python?",
    "What is quantum computing?",   # not in knowledge base — should detect gap
]

for query in test_queries:
    result = retrieve(query, n_results=2)
    print(f"Query: {query}")
    print(f"Confidence: {result['top_confidence']} [{result['assessment']}]")
    print(f"Top result: {result['results'][0]['title']} [{result['results'][0]['topic']}]")
    if result['gap_detected']:
        print("⚠️  KNOWLEDGE GAP DETECTED")
    print()

def retrieve(query, n_results=3, min_confidence=0.45):
    """
    Retrieve most relevant documents for a query.
    Calibrated for all-MiniLM-L6-v2 confidence score range.

    Confidence thresholds (calibrated):
        >= 0.50 → HIGH confidence — good answer available
        >= 0.45 → MEDIUM confidence — partial answer available
        <  0.45 → LOW — knowledge gap likely
    """
    # Step 1 — embed the query
    query_embedding = embedding_model.encode([query]).tolist()

    # Step 2 — search ChromaDB
    results = collection.query(
        query_embeddings=query_embedding,
        n_results=n_results,
        include=['documents', 'metadatas', 'distances']
    )

    # Step 3 — convert distances to confidence scores
    retrieved = []
    for i in range(len(results['documents'][0])):
        distance   = results['distances'][0][i]
        confidence = round(1 / (1 + distance), 3)
        retrieved.append({
            'content':    results['documents'][0][i],
            'title':      results['metadatas'][0][i]['title'],
            'topic':      results['metadatas'][0][i]['topic'],
            'id':         results['metadatas'][0][i]['id'],
            'confidence': confidence,
            'distance':   round(distance, 4)
        })

    # Step 4 — assess confidence with calibrated thresholds
    top_confidence = retrieved[0]['confidence'] if retrieved else 0.0

    if top_confidence >= 0.50:
        assessment   = "HIGH"
        gap_detected = False
    elif top_confidence >= 0.45:
        assessment   = "MEDIUM"
        gap_detected = False
    else:
        assessment   = "LOW — knowledge gap likely"
        gap_detected = True

    return {
        'query':          query,
        'results':        retrieved,
        'top_confidence': top_confidence,
        'assessment':     assessment,
        'gap_detected':   gap_detected
    }

# ── Re-test with calibrated thresholds ──
print("Testing with calibrated thresholds...\n")

test_queries = [
    "What is RAG and how does it work?",
    "How does inter-annotator agreement work?",
    "What is a transformer in AI?",
    "How do I use ChromaDB in Python?",
    "What is quantum computing?",
    "How do I invest in stocks?",
    "What is LangChain used for?",
    "How does RLHF work?",
]

for query in test_queries:
    result = retrieve(query, n_results=2)
    gap_icon = "⚠️  GAP" if result['gap_detected'] else "✅"
    print(f"{gap_icon} [{result['assessment']:28s}] {result['top_confidence']} | {query}")
    print(f"      Top match: {result['results'][0]['title']}")
    print()

def retrieve(query, n_results=3, min_confidence=0.44):
    """
    Retrieve most relevant documents for a query.

    Confidence thresholds (final calibration):
        >= 0.50 → HIGH   — strong answer available
        >= 0.44 → MEDIUM — partial answer available
        <  0.44 → LOW    — knowledge gap detected
    """
    query_embedding = embedding_model.encode([query]).tolist()

    results = collection.query(
        query_embeddings=query_embedding,
        n_results=n_results,
        include=['documents', 'metadatas', 'distances']
    )

    retrieved = []
    for i in range(len(results['documents'][0])):
        distance   = results['distances'][0][i]
        confidence = round(1 / (1 + distance), 3)
        retrieved.append({
            'content':    results['documents'][0][i],
            'title':      results['metadatas'][0][i]['title'],
            'topic':      results['metadatas'][0][i]['topic'],
            'id':         results['metadatas'][0][i]['id'],
            'confidence': confidence,
            'distance':   round(distance, 4)
        })

    top_confidence = retrieved[0]['confidence'] if retrieved else 0.0

    if top_confidence >= 0.50:
        assessment   = "HIGH"
        gap_detected = False
    elif top_confidence >= 0.44:
        assessment   = "MEDIUM"
        gap_detected = False
    else:
        assessment   = "LOW — knowledge gap detected"
        gap_detected = True

    return {
        'query':          query,
        'results':        retrieved,
        'top_confidence': top_confidence,
        'assessment':     assessment,
        'gap_detected':   gap_detected
    }

# ── Final validation test ──
print("="*60)
print("RETRIEVAL SYSTEM — FINAL VALIDATION")
print("="*60)

validation_queries = [
    # Should be HIGH or MEDIUM — in knowledge base
    ("What is RAG?",                          "IN KB"),
    ("How does inter-annotator agreement work?", "IN KB"),
    ("What is a transformer in AI?",          "IN KB"),
    ("How do I use ChromaDB?",                "IN KB"),
    ("What is LangChain?",                    "IN KB"),
    ("How does RLHF work?",                   "IN KB"),
    ("What is prompt engineering?",           "IN KB"),
    ("How does data annotation work?",        "IN KB"),
    # Should be LOW — not in knowledge base
    ("What is quantum computing?",            "NOT IN KB"),
    ("How do I invest in stocks?",            "NOT IN KB"),
    ("What is the weather in Boston?",        "NOT IN KB"),
    ("How do I cook pasta?",                  "NOT IN KB"),
]

correct = 0
total   = len(validation_queries)

for query, expected in validation_queries:
    result   = retrieve(query, n_results=1)
    in_kb    = not result['gap_detected']
    expected_in_kb = expected == "IN KB"
    is_correct     = in_kb == expected_in_kb
    correct  += 1 if is_correct else 0
    status   = "✅ CORRECT" if is_correct else "❌ WRONG"
    gap_icon = "📚" if in_kb else "⚠️ "
    print(f"{status} {gap_icon} [{result['top_confidence']}] {query}")

print(f"\nAccuracy: {correct}/{total} ({correct/total*100:.0f}%)")
print("\nRetrieval system calibrated and ready!")

!pip install groq -q
print("Groq installed!")

from groq import Groq

# ── Initialize Groq client ──
GROQ_API_KEY = "YOUR_GROQ_API_KEY_HERE"
groq_client = Groq(api_key=GROQ_API_KEY)
print("Groq connected successfully!")

# ── Test connection with current model ──
test = groq_client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": "Say hello in one sentence."}],
    max_tokens=50
)
print("Test response:", test.choices[0].message.content)
print("\nGroq + LLaMA 3.1 ready!")

def ask(query, n_results=3, show_sources=True):
    """
    Full RAG Q&A function with citations and gap detection.
    Uses Groq + LLaMA 3.1 as the LLM backend.
    """
    print(f"\n{'='*60}")
    print(f"Question: {query}")
    print('='*60)

    # Step 1 — retrieve relevant documents
    retrieval = retrieve(query, n_results=n_results)

    # Step 2 — handle knowledge gap
    if retrieval['gap_detected']:
        gap_message = (
            f"⚠️  KNOWLEDGE GAP DETECTED\n"
            f"This topic is not covered in your knowledge base.\n"
            f"Top match was '{retrieval['results'][0]['title']}' "
            f"with only {retrieval['top_confidence']} confidence.\n"
            f"Suggested action: Add study notes about this topic."
        )
        print(f"Confidence: {retrieval['top_confidence']} [{retrieval['assessment']}]")
        print(f"\n{gap_message}")
        return {
            'query':       query,
            'answer':      None,
            'gap':         True,
            'gap_message': gap_message,
            'confidence':  retrieval['top_confidence'],
            'sources':     []
        }

    # Step 3 — build context from retrieved documents
    context_parts = []
    for i, doc in enumerate(retrieval['results'], 1):
        context_parts.append(
            f"[Source {i}: {doc['title']} — {doc['topic']}]\n{doc['content']}"
        )
    context = "\n\n".join(context_parts)

    # Step 4 — build augmented prompt
    system_prompt = """You are an expert AI/ML tutor helping a graduate student
prepare for AI and Data Science internships. Answer questions clearly and
concisely using only the provided context. Always cite your sources by
mentioning the source title. If the context does not fully answer the question,
say what IS covered and what additional study might help."""

    user_prompt = f"""Answer this question using the provided context:

Question: {query}

Context:
{context}

Provide a clear, well-structured answer in 3-5 sentences.
Cite sources naturally in your response.
End with: "Sources: [list the source titles used]"
"""

    # Step 5 — call Groq API
    print(f"Confidence: {retrieval['top_confidence']} [{retrieval['assessment']}]")
    print(f"Retrieved {len(retrieval['results'])} sources — generating answer...\n")

    response = groq_client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_prompt}
        ],
        max_tokens=500,
        temperature=0.3
    )

    answer = response.choices[0].message.content

    # Step 6 — build sources list
    sources = [{
        'title':      doc['title'],
        'topic':      doc['topic'],
        'confidence': doc['confidence']
    } for doc in retrieval['results']]

    # Step 7 — display
    print(answer)
    if show_sources:
        print(f"\n📚 Retrieved sources:")
        for src in sources:
            print(f"   [{src['confidence']}] {src['title']} — {src['topic']}")

    return {
        'query':      query,
        'answer':     answer,
        'gap':        False,
        'confidence': retrieval['top_confidence'],
        'assessment': retrieval['assessment'],
        'sources':    sources
    }


# ── Test with 5 questions ──
r1 = ask("What is RAG and why is it important?")
r2 = ask("How does inter-annotator agreement affect data quality?")
r3 = ask("What is LangChain used for in agentic AI?")
r4 = ask("How do I use ChromaDB in Python?")
r5 = ask("What is quantum computing?")  # gap test

import random

def generate_quiz(topic=None, num_questions=5):
    """
    Generate a quiz from the knowledge base.
    If topic is specified, generates questions for that topic only.
    If topic is None, generates questions across all topics.
    """
    print(f"\n{'='*60}")
    if topic:
        print(f"QUIZ — Topic: {topic}")
    else:
        print(f"QUIZ — Mixed topics")
    print('='*60)

    # Step 1 — select documents to quiz on
    if topic:
        topic_docs = [doc for doc in knowledge_base
                      if doc['topic'].lower() == topic.lower()]
        if not topic_docs:
            print(f"Topic '{topic}' not found in knowledge base.")
            print(f"Available topics: {list(set(d['topic'] for d in knowledge_base))}")
            return None
        selected_docs = random.sample(
            topic_docs, min(num_questions, len(topic_docs))
        )
    else:
        selected_docs = random.sample(
            knowledge_base, min(num_questions, len(knowledge_base))
        )

    # Step 2 — build quiz generation prompt
    docs_text = ""
    for i, doc in enumerate(selected_docs, 1):
        docs_text += f"\nDocument {i} [{doc['topic']}]: {doc['title']}\n{doc['content'][:300]}...\n"

    prompt = f"""You are an expert AI/ML tutor creating a quiz for a graduate student
preparing for AI internships.

Based on the following study materials, generate exactly {num_questions} multiple choice
questions. Each question must have 4 options (A, B, C, D) and one correct answer.

Study materials:
{docs_text}

Format each question EXACTLY like this:
Q1: [question text]
A) [option]
B) [option]
C) [option]
D) [option]
Answer: [correct letter]
Explanation: [one sentence explaining why]

Generate {num_questions} questions now:"""

    # Step 3 — call Groq
    response = groq_client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=1500,
        temperature=0.7
    )

    quiz_text = response.choices[0].message.content

    # Step 4 — parse quiz into structured format
    questions = []
    lines = quiz_text.strip().split('\n')
    current_q = {}

    for line in lines:
        line = line.strip()
        if not line:
            continue
        if line.startswith('Q') and ':' in line and len(line) < 200:
            if current_q and 'question' in current_q:
                questions.append(current_q)
            current_q = {'question': line.split(':', 1)[1].strip(),
                         'options': {}, 'answer': '', 'explanation': ''}
        elif line.startswith(('A)', 'B)', 'C)', 'D)')):
            letter = line[0]
            current_q['options'][letter] = line[3:].strip()
        elif line.startswith('Answer:'):
            current_q['answer'] = line.replace('Answer:', '').strip()
        elif line.startswith('Explanation:'):
            current_q['explanation'] = line.replace('Explanation:', '').strip()

    if current_q and 'question' in current_q:
        questions.append(current_q)

    # Step 5 — display quiz interactively
    print(f"\nGenerated {len(questions)} questions. Let's begin!\n")

    score = 0
    results = []

    for i, q in enumerate(questions, 1):
        print(f"Q{i}: {q['question']}")
        for letter, option in q['options'].items():
            print(f"   {letter}) {option}")

        # Get user answer
        while True:
            user_answer = input("\nYour answer (A/B/C/D) or 'skip': ").strip().upper()
            if user_answer in ['A', 'B', 'C', 'D', 'SKIP']:
                break
            print("Please enter A, B, C, D, or 'skip'")

        if user_answer == 'SKIP':
            print(f"Skipped. Correct answer: {q['answer']}")
            print(f"Explanation: {q['explanation']}\n")
            results.append({'question': q['question'], 'status': 'skipped',
                           'correct_answer': q['answer']})
        elif user_answer == q['answer']:
            score += 1
            print(f"✅ Correct! {q['explanation']}\n")
            results.append({'question': q['question'], 'status': 'correct',
                           'user_answer': user_answer, 'correct_answer': q['answer']})
        else:
            print(f"❌ Incorrect. Correct answer: {q['answer']}")
            print(f"Explanation: {q['explanation']}\n")
            results.append({'question': q['question'], 'status': 'incorrect',
                           'user_answer': user_answer, 'correct_answer': q['answer']})

    # Step 6 — show score
    answered = len([r for r in results if r['status'] != 'skipped'])
    print(f"\n{'='*60}")
    print(f"QUIZ COMPLETE — Score: {score}/{answered} ({score/max(answered,1)*100:.0f}%)")
    print('='*60)

    if answered > 0:
        pct = score / answered * 100
        if pct >= 80:
            print("🌟 Excellent! You have strong understanding of this material.")
        elif pct >= 60:
            print("👍 Good work! Review the questions you missed.")
        else:
            print("📚 Keep studying! Focus on the topics you missed.")

    # Step 7 — identify weak topics
    weak_topics = []
    for r in results:
        if r['status'] == 'incorrect':
            weak_topics.append(r['question'][:50])

    if weak_topics:
        print(f"\n⚠️  Topics to review:")
        for t in weak_topics:
            print(f"   → {t}...")

    return {
        'score':       score,
        'total':       answered,
        'percentage':  score / max(answered, 1) * 100,
        'results':     results,
        'weak_topics': weak_topics
    }


# ── Test the quiz generator ──
print("Starting quiz on Data Annotation...")
print("Answer each question by typing A, B, C, or D\n")
quiz_result = generate_quiz(topic="Data Annotation", num_questions=3)

def ask(query, n_results=3, show_sources=True):
    """
    Full RAG Q&A function with citations and gap detection.
    Uses Groq + LLaMA 3.1 as the LLM backend.
    """
    print(f"\n{'='*60}")
    print(f"Question: {query}")
    print('='*60)

    retrieval = retrieve(query, n_results=n_results)

    # Handle knowledge gap
    if retrieval['gap_detected']:
        gap_message = (
            f"⚠️  KNOWLEDGE GAP DETECTED\n"
            f"This topic is not covered in your knowledge base.\n"
            f"Top match was '{retrieval['results'][0]['title']}' "
            f"with only {retrieval['top_confidence']} confidence.\n"
            f"Suggested action: Add study notes about this topic."
        )
        print(f"Confidence: {retrieval['top_confidence']} [{retrieval['assessment']}]")
        print(f"\n{gap_message}")
        return {
            'query':       query,
            'answer':      None,
            'gap':         True,
            'gap_message': gap_message,
            'confidence':  retrieval['top_confidence'],
            'assessment':  retrieval['assessment'],   # ← fixed: added this
            'sources':     []
        }

    # Build context
    context_parts = []
    for i, doc in enumerate(retrieval['results'], 1):
        context_parts.append(
            f"[Source {i}: {doc['title']} — {doc['topic']}]\n{doc['content']}"
        )
    context = "\n\n".join(context_parts)

    # Build prompt
    system_prompt = """You are an expert AI/ML tutor helping a graduate student
prepare for AI and Data Science internships. Answer questions clearly and
concisely using only the provided context. Always cite your sources by
mentioning the source title."""

    user_prompt = f"""Answer this question using the provided context:

Question: {query}

Context:
{context}

Provide a clear answer in 3-5 sentences. Cite sources naturally.
End with: "Sources: [list the source titles used]"
"""

    print(f"Confidence: {retrieval['top_confidence']} [{retrieval['assessment']}]")
    print(f"Retrieved {len(retrieval['results'])} sources — generating answer...\n")

    response = groq_client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_prompt}
        ],
        max_tokens=500,
        temperature=0.3
    )

    answer  = response.choices[0].message.content
    sources = [{
        'title':      doc['title'],
        'topic':      doc['topic'],
        'confidence': doc['confidence']
    } for doc in retrieval['results']]

    print(answer)
    if show_sources:
        print(f"\n📚 Retrieved sources:")
        for src in sources:
            print(f"   [{src['confidence']}] {src['title']} — {src['topic']}")

    return {
        'query':      query,
        'answer':     answer,
        'gap':        False,
        'confidence': retrieval['top_confidence'],
        'assessment': retrieval['assessment'],
        'sources':    sources
    }


# ── Re-run the full system test ──
print("Testing full integrated system...\n")

ask_tracked("What is RAG and why is it important?")
ask_tracked("How does inter-annotator agreement work?")
ask_tracked("What is LangChain used for?")
ask_tracked("What is quantum computing?")
ask_tracked("How do I invest in stocks?")

# Show dashboard
show_dashboard()

# ── Run quizzes on 3 different topics ──
print("Running quizzes to populate dashboard...\n")
print("Answer each question with A, B, C, or D\n")

# Quiz 1 — RAG
q1 = quiz_tracked(topic="RAG", num_questions=3)

# Quiz 2 — Vector Databases
q2 = quiz_tracked(topic="Vector Databases", num_questions=2)

# Quiz 3 — Mixed topics
q3 = quiz_tracked(topic=None, num_questions=3)

# Show updated dashboard
show_dashboard()